// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_pwd.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPassword = `-- name: GetPassword :one
SELECT hashed_password
FROM users
WHERE id = $1
`

func (q *Queries) GetPassword(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getPassword, id)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
